-- MySQL Script generated by MySQL Workbench
-- Wed Nov 11 07:27:54 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `title_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `title_type` (
  `type_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netflix_titles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `netflix_titles` (
  `showid` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `date_added` DATE NULL,
  `release_year` INT NULL,
  `rating` VARCHAR(45) NULL,
  `duration` VARCHAR(45) NULL,
  `description` VARCHAR(100) NULL,
  `title_type_type_id` INT NOT NULL,
  PRIMARY KEY (`showid`, `title_type_type_id`),
  INDEX `fk_netflix_titles_title_type_idx` (`title_type_type_id` ASC)     ,
  CONSTRAINT `fk_netflix_titles_title_type`
    FOREIGN KEY (`title_type_type_id`)
    REFERENCES `title_type` (`type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `country_produced`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `country_produced` (
  `country_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`country_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genre` (
  `genre_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`genre_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cast`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cast` (
  `cast_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`cast_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `director`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `director` (
  `director_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`director_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netflix_titles_has_director`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `netflix_titles_has_director` (
  `netflix_titles_showid` INT NOT NULL,
  `director_director_id` INT NOT NULL,
  PRIMARY KEY (`netflix_titles_showid`, `director_director_id`),
  INDEX `fk_netflix_titles_has_director_director1_idx` (`director_director_id` ASC)     ,
  INDEX `fk_netflix_titles_has_director_netflix_titles1_idx` (`netflix_titles_showid` ASC)     ,
  CONSTRAINT `fk_netflix_titles_has_director_netflix_titles1`
    FOREIGN KEY (`netflix_titles_showid`)
    REFERENCES `netflix_titles` (`showid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_netflix_titles_has_director_director1`
    FOREIGN KEY (`director_director_id`)
    REFERENCES `director` (`director_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netflix_titles_has_cast`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `netflix_titles_has_cast` (
  `netflix_titles_showid` INT NOT NULL,
  `cast_cast_id` INT NOT NULL,
  PRIMARY KEY (`netflix_titles_showid`, `cast_cast_id`),
  INDEX `fk_netflix_titles_has_cast_cast1_idx` (`cast_cast_id` ASC)     ,
  INDEX `fk_netflix_titles_has_cast_netflix_titles1_idx` (`netflix_titles_showid` ASC)     ,
  CONSTRAINT `fk_netflix_titles_has_cast_netflix_titles1`
    FOREIGN KEY (`netflix_titles_showid`)
    REFERENCES `netflix_titles` (`showid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_netflix_titles_has_cast_cast1`
    FOREIGN KEY (`cast_cast_id`)
    REFERENCES `cast` (`cast_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netflix_titles_has_country_produced`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `netflix_titles_has_country_produced` (
  `netflix_titles_showid` INT NOT NULL,
  `country_produced_country_id` INT NOT NULL,
  PRIMARY KEY (`netflix_titles_showid`, `country_produced_country_id`),
  INDEX `fk_netflix_titles_has_country_produced_country_produced1_idx` (`country_produced_country_id` ASC)     ,
  INDEX `fk_netflix_titles_has_country_produced_netflix_titles1_idx` (`netflix_titles_showid` ASC)     ,
  CONSTRAINT `fk_netflix_titles_has_country_produced_netflix_titles1`
    FOREIGN KEY (`netflix_titles_showid`)
    REFERENCES `netflix_titles` (`showid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_netflix_titles_has_country_produced_country_produced1`
    FOREIGN KEY (`country_produced_country_id`)
    REFERENCES `country_produced` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netflix_titles_has_genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `netflix_titles_has_genre` (
  `netflix_titles_showid` INT NOT NULL,
  `genre_genre_id` INT NOT NULL,
  PRIMARY KEY (`netflix_titles_showid`, `genre_genre_id`),
  INDEX `fk_netflix_titles_has_genre_genre1_idx` (`genre_genre_id` ASC)     ,
  INDEX `fk_netflix_titles_has_genre_netflix_titles1_idx` (`netflix_titles_showid` ASC)     ,
  CONSTRAINT `fk_netflix_titles_has_genre_netflix_titles1`
    FOREIGN KEY (`netflix_titles_showid`)
    REFERENCES `netflix_titles` (`showid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_netflix_titles_has_genre_genre1`
    FOREIGN KEY (`genre_genre_id`)
    REFERENCES `genre` (`genre_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
